### ISSUE TITLE
Compatibility with FastClosures

### ISSUE THREAD

**Issue by oschulz** [haberdashPI/LambdaFn.jl#5]
Currently,

```julia
using LambdaFn, FastClosures
@closure(@λ(_ + _))
```

fails (`ArgumentError: Argument to @closure must be a closure!`).

Would be nice if `@closure` and `@λ` could be combined - on the other hand, it also get's a bit verbose, and I guess the main point of `@λ` is to keep things very concise. But maybe `@λ` could use `FastClosures` internally, and always  implement the closures workaround automatically?

**Comment by haberdashPI** [comment]
Sorry for not getting back to you, I lost the email notification for this issue when I was clearing my inbox after having a baby (10K+ emails!!!); just noticed it now.

I was not aware of FastClosures. Seems to me the easiest way to fix this would be to make a change in the `@closure` macro to be aware of   `@lf` and `@λ`. 

That said, I really like [Underscore.jl](https://github.com/c42f/Underscore.jl), and think it is probably a more elegant solution than LambadaFn. I will probably be using that instead of this package. 

That, combined with the point you raise—that this `_` notation is mostly for brevity, and `@closure` is long and can still be used with `->` notation—leaves me unmotivated to fix this.

I also suspect it would be easier to make Underscore work with FastClosures, because you could just write `@_ map( @closure(_ + _), bla bla bla...`: @c42f would probably know better.

**Comment by oschulz** [comment]
No worries, I'll close this for now, then. Looks like we'll have native support for `_` in Julia soon, anyhow (JuliaLang/julia#24990) :-)
